# CÓDIGO: docker-compose.yml (RAÍZ DEL PROYECTO)
version: '3.8'

services:
  # 1. SERVICIO DE BACKEND (API de ML)
  backend-api:
    container_name: energy-predictor-api
    build:
      context: . 
      dockerfile: backend/Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}" # Mapeo usando .env (8000:8000)
    networks:
      - energy_net
    # Usa las variables definidas en .env
    env_file:
      - .env
    restart: always

  # 2. SERVICIO DE FRONTEND (Streamlit)
  frontend-web:
    container_name: energy-predictor-web
    build:
      context: . 
      dockerfile: frontend/Dockerfile 
    ports:
      - "8501:8501" # Mapeamos al 8501 por defecto de Streamlit
    networks:
      - energy_net
    depends_on:
      - backend-api 
    restart: always

# 3. DEFINICIÓN DE REDES
networks:
  energy_net:
    driver: bridge